name: Release

on:
  push:
    tags:
      - '*'  # This means the action runs on every push to a tag

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Verify tag
        run: |
          echo "Tag: $GITHUB_REF"
          if [ -z "$GITHUB_REF" ]; then
            echo "No tag found."
            exit 1

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*  # Path to any files you want to attach to the release (optional)
        env:GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}