name: Release

on:
  push:
    tags:
      - '*'  # This means the action runs on every push to a tag starting with 'v'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: bump2version minor --allow-dirty --tag

      - name: Commit version bump
        run: git commit -am "Bump version to $(cat version.txt)"

      - name: Force push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - name: Push tags
        run: git push origin --tags --force

      - name: Wait for tag to be available
        run: sleep 10

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*  # Path to any files you want to attach to the release (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}