name: Release

on:
  push:
    branches:
      - main  # This means the action runs on every push to the 'main' branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version
        run: bump2version minor --new-version <NEW_VERSION> --allow-dirty --tag
        env:
          NEW_VERSION: 1.0.6  # Replace this with the appropriate version

      - name: Commit version bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Bump version to $NEW_VERSION"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Push tags
        run: git push origin --tags

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*  # Path to any files you want to attach to the release (optional)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}